#ifndef BKPRAM_LAYOUT_H
#define BKPRAM_LAYOUT_H

  #define GC_ID_LENGTH		        	1
  #define GC_MAC_LENGTH 	        	6
  #define GC_LOCAL_IP_LENGTH 	        4
  #define GC_LOCAL_PORT_LENGTH 	        1
  #define GC_REMOTE_IP_LENGTH 	        4
  #define GC_REMOTE_PORT_LENGTH         1
  #define GC_NETMASK_LENGTH 	        4
  #define GC_GATEWAY_LENGTH 	        4
  #define GC_LATITUDE_LENGTH 	        4
  #define GC_LONGITUDE_LENGTH 	        4
  #define GC_PHONE_LENGTH 	        	12
  #define GC_CALIBRATION_LENGTH         4


  #define GC_ID_LOCATION	        	0
  #define GC_MAC_LOCATION               (GC_ID_LOCATION + GC_ID_LENGTH)
  #define GC_LOCAL_IP_LOCATION 	        (GC_MAC_LOCATION + GC_MAC_LENGTH)
  #define GC_LOCAL_PORT_LOCATION 		(GC_LOCAL_IP_LOCATION + GC_LOCAL_IP_LENGTH)
  #define GC_REMOTE_IP_LOCATION         (GC_LOCAL_PORT_LOCATION + GC_LOCAL_PORT_LENGTH)
  #define GC_REMOTE_PORT_LOCATION 		(GC_REMOTE_IP_LOCATION + GC_REMOTE_IP_LENGTH)
  #define GC_NETMASK_LOCATION 	        (GC_REMOTE_PORT_LOCATION + GC_REMOTE_PORT_LENGTH)
  #define GC_GATEWAY_LOCATION           (GC_NETMASK_LOCATION + GC_NETMASK_LENGTH)
  #define GC_LATITUDE_LOCATION 	        (GC_GATEWAY_LOCATION + GC_GATEWAY_LENGTH)
  #define GC_LONGITUDE_LOCATION         (GC_LATITUDE_LOCATION + GC_LATITUDE_LENGTH)
  #define GC_PHONE_LOCATION             (GC_LONGITUDE_LOCATION + GC_LONGITUDE_LENGTH)
  #define GC_CALIBRATION_TX             (GC_PHONE_LOCATION + GC_CALIBRATION_LENGTH)
  #define GC_CALIBRATION_RX             (GC_CALIBRATION_TX + GC_CALIBRATION_LENGTH)

 
#endif

